version: '3'

services:
  metrics:
    build: ./metrics
    networks:
      - mybridge
    ports:
      - "9090:9090"

  traces:
    build: ./traces
    networks:
      - mybridge
    ports:
      - "9411:9411"

  grafana:
    build: ./grafana
    networks:
      - mybridge
    ports:
      - "3000:3000"
    depends_on:
      - metrics

networks:
  mybridge:
