consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  RatingPayload:
    example:
      movieId: 138493
      rating: 3.5
      userId: 56757
    properties:
      movieId:
        example: 138493
        minimum: 1
        type: integer
      rating:
        example: 3.5
        maximum: 5
        minimum: 0.5
        type: number
      userId:
        example: 56757
        minimum: 1
        type: integer
    required:
    - movieId
    - userId
    - rating
    title: RatingPayload
    type: object
  rating:
    description: A movie rating by a user (default view)
    example:
      movieId: 138493
      rating: 3.5
      userId: 56757
    properties:
      movieId:
        example: 138493
        minimum: 1
        type: integer
      rating:
        example: 3.5
        maximum: 5
        minimum: 0.5
        type: number
      userId:
        example: 56757
        minimum: 1
        type: integer
    required:
    - movieId
    - userId
    - rating
    title: 'Mediatype identifier: application/cassandra.wannabe.rating+json; view=default'
    type: object
host: localhost:8080
info:
  description: CRUD API for a distributed database.
  license:
    name: MIT
    url: https://github.com/freddygv/cassandra-wannabe/blob/master/LICENSE
  title: The Cassandra-Wannabe API
  version: ""
paths:
  /db/v1/:
    put:
      description: Adds a rating record
      operationId: rating#upsert
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RatingPayload'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: upsert rating
      tags:
      - rating
  /db/v1/{movieId}/{userId}:
    delete:
      description: Delete rating record
      operationId: rating#delete
      parameters:
      - in: path
        name: movieId
        required: true
        type: integer
      - in: path
        name: userId
        required: true
        type: integer
      responses:
        "202":
          description: Accepted
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: delete rating
      tags:
      - rating
    get:
      description: Retrieves a rating record
      operationId: rating#read
      parameters:
      - in: path
        name: movieId
        required: true
        type: integer
      - in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/cassandra.wannabe.rating+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rating'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: read rating
      tags:
      - rating
  /db/v1/status:
    get:
      description: Status of the API.
      operationId: health#health
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: health health
      tags:
      - health
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download public/swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Accepted:
    description: Accepted
  InternalServerError:
    description: Internal Server Error
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
